from . import selections
from . import crm_lead
from . import crm_stage
from . import ir_ui_view
from . import res_company
from . import res_partner
from . import res_users
from . import sale_order
from . import utm_source
