[options]
admin_passwd = $pbkdf2-sha512$600000$itE6x9h7b02JkRLiPGcM4Q$7VxrN1vmxShqHLhFwO83CPvqyTrlzmt.Jw86KW9K19J0T6jiv4ZwBqcimBX8eX0zs9k1UNSLzt17VxyIs0n3LA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = .*
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = False
list_db = True
without_demo = True
limit_time_cpu = 120
limit_time_real = 240
