{
    "name": "DigiPlus CRM",
    "summary": "CRM B2B structure pour DigiPlus Consulting.",
    "version": "18.0.1.0.0",
    "category": "Sales/CRM",
    "author": "DigiPlus Consulting",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "mail",
        "contacts",
        "sale_management",
        "sale_crm",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/company_branding_data.xml",
        "data/company_currency_normalization_data.xml",
        "data/language_sanitization_data.xml",
        "data/crm_stage_data.xml",
        "data/crm_activity_type_data.xml",
        "data/crm_source_data.xml",
        "data/crm_cron_data.xml",
        "views/crm_lead_views.xml",
        "views/crm_lead_search_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/crm_dashboard_views.xml",
        "views/crm_import_wizard_views.xml",
        "views/crm_menu_views.xml",
        "data/pipeline_view_normalization_data.xml",
        "reports/crm_dashboard_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "digiplus_crm/static/src/css/crm_dashboard.css",
            "digiplus_crm/static/src/css/crm_pipeline.css",
        ],
    },
    "installable": True,
    "application": False,
}
