{
    "name": "DigiPlus Consulting Operations",
    "summary": "Operational workspace for DigiPlus Consulting CRM, sales, services and reporting.",
    "version": "18.0.1.0.0",
    "category": "Sales/CRM",
    "author": "DigiPlus Consulting",
    "license": "LGPL-3",
    "depends": [
        "digiplus_crm",
        "crm",
        "sale_management",
        "contacts",
        "mail",
        "mass_mailing",
        "stock",
        "purchase",
        "account",
        "product",
        "sale_stock",
    ],
    "data": [
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "data/crm_stages.xml",
        "data/crm_tags.xml",
        "data/activity_types.xml",
        "data/service_categories.xml",
        "data/base_partners.xml",
        "data/base_products_services.xml",
        "data/base_opportunities.xml",
        "data/base_activities.xml",
        "data/base_sale_orders.xml",
        "data/base_purchase_orders.xml",
        "data/base_invoices.xml",
        "data/base_whatsapp_messages.xml",
        "data/email_templates.xml",
        "data/marketing_campaigns.xml",
        "data/dashboard_metrics.xml",
        "data/automated_actions.xml",
        "views/crm_lead_views.xml",
        "views/crm_lead_kanban_views.xml",
        "views/crm_lead_search_views.xml",
        "views/crm_lead_graph_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/product_template_views.xml",
        "views/stock_picking_views.xml",
        "views/purchase_order_views.xml",
        "views/account_move_views.xml",
        "views/marketing_views.xml",
        "views/whatsapp_message_views.xml",
        "views/dashboard_views.xml",
        "views/menu_views.xml",
        "reports/sale_order_report.xml",
        "reports/invoice_report.xml",
        "reports/stock_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "digiplus_agrochem_demo/static/src/css/demo_theme.css",
            "digiplus_agrochem_demo/static/src/js/demo_dashboard.js",
        ],
    },
    "installable": True,
    "application": True,
}
