from . import account_move
from . import crm_lead
from . import dashboard_metric
from . import marketing_campaign
from . import product_template
from . import purchase_order
from . import res_partner
from . import sale_order
from . import stock_picking
from . import whatsapp_message
